### ISSUE TITLE
AssertionError in Tornado

### ISSUE THREAD

**Issue by kj7rrv** [kj7rrv/hcra#17]
I guess the switch to Tornado didn't improve stability. It now does this occasionally:

    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.8/threading.py", line 870, in run
        self._target(*self._args, **self._kwargs)
      File "wss.py", line 83, in run
        loop.run_until_complete(self.cycle())
      File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "wss.py", line 73, in cycle
        self.write_message(item)
      File "/home/kj7rrv/.local/lib/python3.8/site-packages/tornado/websocket.py", line 340, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/kj7rrv/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1096, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/kj7rrv/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1073, in _write_frame
        return self.stream.write(frame)
      File "/home/kj7rrv/.local/lib/python3.8/site-packages/tornado/iostream.py", line 544, in write
        self._handle_write()
      File "/home/kj7rrv/.local/lib/python3.8/site-packages/tornado/iostream.py", line 974, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/kj7rrv/.local/lib/python3.8/site-packages/tornado/iostream.py", line 183, in advance
        assert 0 < size <= self._size
    AssertionError

## Steps to reproduce
1. Connect
2. Wait

**Comment by kj7rrv** [comment]
Closed by 94fa2bf.
